version: 0.2
env:
  variables:
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
     commands:
      - echo Build completed on `date`
artifacts:
  files:
  base-directory: 'dist*'
  discard-paths: yes